// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Toggle struct {
	ID        int64          `json:"id"`
	State     bool           `json:"state"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt sql.NullTime   `json:"created_at"`
	IpHash    string         `json:"ip_hash"`
	Uuid      string         `json:"uuid"`
}
