// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: toggles.sql

package store

import (
	"context"
	"database/sql"
)

const getLatestToggle = `-- name: GetLatestToggle :one
SELECT id, state, reason, created_at, ip_hash FROM toggles
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestToggle(ctx context.Context) (Toggle, error) {
	row := q.db.QueryRowContext(ctx, getLatestToggle)
	var i Toggle
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.IpHash,
	)
	return i, err
}

const getRecentToggles = `-- name: GetRecentToggles :many
SELECT id, state, reason, created_at, ip_hash FROM toggles
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetRecentToggles(ctx context.Context, limit int64) ([]Toggle, error) {
	rows, err := q.db.QueryContext(ctx, getRecentToggles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Toggle
	for rows.Next() {
		var i Toggle
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Reason,
			&i.CreatedAt,
			&i.IpHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToggle = `-- name: InsertToggle :one
INSERT INTO toggles (state, reason, ip_hash)
VALUES (?, ?, ?)
RETURNING id, state, reason, created_at, ip_hash
`

type InsertToggleParams struct {
	State  bool           `json:"state"`
	Reason sql.NullString `json:"reason"`
	IpHash string         `json:"ip_hash"`
}

func (q *Queries) InsertToggle(ctx context.Context, arg InsertToggleParams) (Toggle, error) {
	row := q.db.QueryRowContext(ctx, insertToggle, arg.State, arg.Reason, arg.IpHash)
	var i Toggle
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.IpHash,
	)
	return i, err
}

const pruneOldToggles = `-- name: PruneOldToggles :exec
DELETE FROM toggles
WHERE id NOT IN (
    SELECT id FROM toggles ORDER BY id DESC LIMIT ?
)
`

func (q *Queries) PruneOldToggles(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneOldToggles, limit)
	return err
}
