// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: toggles.sql

package store

import (
	"context"
	"database/sql"
)

const getLatestToggle = `-- name: GetLatestToggle :one
SELECT id, state, reason, created_at, ip_hash, uuid FROM toggles
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestToggle(ctx context.Context) (Toggle, error) {
	row := q.db.QueryRowContext(ctx, getLatestToggle)
	var i Toggle
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.IpHash,
		&i.Uuid,
	)
	return i, err
}

const getRecentToggles = `-- name: GetRecentToggles :many
SELECT id, state, reason, created_at, ip_hash, uuid FROM toggles
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetRecentToggles(ctx context.Context, limit int64) ([]Toggle, error) {
	rows, err := q.db.QueryContext(ctx, getRecentToggles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Toggle
	for rows.Next() {
		var i Toggle
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Reason,
			&i.CreatedAt,
			&i.IpHash,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTogglesBefore = `-- name: GetTogglesBefore :many
SELECT id, state, reason, created_at, ip_hash, uuid FROM toggles
WHERE id < ?
ORDER BY id DESC
LIMIT ?
`

type GetTogglesBeforeParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

func (q *Queries) GetTogglesBefore(ctx context.Context, arg GetTogglesBeforeParams) ([]Toggle, error) {
	rows, err := q.db.QueryContext(ctx, getTogglesBefore, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Toggle
	for rows.Next() {
		var i Toggle
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Reason,
			&i.CreatedAt,
			&i.IpHash,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToggleByUUID = `-- name: GetToggleByUUID :one
SELECT id, state, reason, created_at, ip_hash, uuid FROM toggles
WHERE uuid = ?
`

func (q *Queries) GetToggleByUUID(ctx context.Context, uuid string) (Toggle, error) {
	row := q.db.QueryRowContext(ctx, getToggleByUUID, uuid)
	var i Toggle
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.IpHash,
		&i.Uuid,
	)
	return i, err
}

const insertToggle = `-- name: InsertToggle :one
INSERT INTO toggles (uuid, state, ip_hash)
VALUES (?, ?, ?)
RETURNING id, state, reason, created_at, ip_hash, uuid
`

type InsertToggleParams struct {
	Uuid   string `json:"uuid"`
	State  bool   `json:"state"`
	IpHash string `json:"ip_hash"`
}

func (q *Queries) InsertToggle(ctx context.Context, arg InsertToggleParams) (Toggle, error) {
	row := q.db.QueryRowContext(ctx, insertToggle, arg.Uuid, arg.State, arg.IpHash)
	var i Toggle
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.IpHash,
		&i.Uuid,
	)
	return i, err
}

const pruneOldToggles = `-- name: PruneOldToggles :exec
DELETE FROM toggles
WHERE id NOT IN (
    SELECT id FROM toggles ORDER BY id DESC LIMIT ?
)
`

func (q *Queries) PruneOldToggles(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneOldToggles, limit)
	return err
}

const updateToggleReason = `-- name: UpdateToggleReason :execresult
UPDATE toggles
SET reason = ?
WHERE uuid = ? AND (reason IS NULL OR reason = '')
`

type UpdateToggleReasonParams struct {
	Reason sql.NullString `json:"reason"`
	Uuid   string         `json:"uuid"`
}

func (q *Queries) UpdateToggleReason(ctx context.Context, arg UpdateToggleReasonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateToggleReason, arg.Reason, arg.Uuid)
}
